SELECT TOP (1000) [CustomerKey]
      ,[GeographyKey]
      ,[Title]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[BirthDate]
      ,[MaritalStatus]
      ,[Gender]
      ,[EmailAddress]
      ,[YearlyIncome]
      ,[TotalChildren]
      ,[EnglishEducation]
      ,[EnglishOccupation]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[Phone]
      ,[DateFirstPurchase]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]
