SELECT TOP (1000) [ProductKey]
      ,[ProductAlternateKey]
      ,[ProductSubcategoryKey]
      ,[EnglishProductName]
      ,[StandardCost]
      ,[Color]
      ,[SafetyStockLevel]
      ,[SizeRange]
      ,[ModelName]
      ,[StartDate]
      ,[EndDate]
      ,[Status]
  FROM [AdventureWorksDW2019].[dbo].[DimProduct]
