SELECT TOP (1000) [ProductKey]
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey]
      ,[CurrencyKey]
      ,[SalesTerritoryKey]
      ,[SalesOrderNumber]
	  ,[SalesOrderLineNumber]
      ,[OrderQuantity]
      ,[UnitPrice]
      ,[SalesAmount]
	  ,[ProductStandardCost]
FROM [AdventureWorksDW2019].[dbo].[FactInternetSales]
